     
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES 
    FROM BOOK_SALES S 
        LEFT JOIN BOOK B
        ON B.BOOK_ID = S.BOOK_ID
        LEFT JOIN AUTHOR A
        ON A.AUTHOR_ID = B.AUTHOR_ID
            WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
                GROUP BY B.AUTHOR_ID, B.CATEGORY
                    ORDER BY AUTHOR_ID, CATEGORY DESC
                