-- 코드를 입력하세요
WITH TOTAL_SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022
        AND MONTH(SALES_DATE) = 1
            GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(TS.SALES * B.PRICE) AS TOTAL_SALES 
    FROM BOOK B
        INNER JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
        INNER JOIN TOTAL_SALES TS
        ON B.BOOK_ID = TS.BOOK_ID
            GROUP BY B.AUTHOR_ID, B.CATEGORY
                ORDER BY B.AUTHOR_ID, B.CATEGORY DESC