WITH TARGET_NAME AS (
    SELECT ANIMAL_ID FROM ANIMAL_INS
        WHERE NAME IN ("Lucy", "Ella", "Pickle", "Rogan", "Sabrina", "Mitty")
)

SELECT AI.ANIMAL_ID, NAME, SEX_UPON_INTAKE
    FROM ANIMAL_INS AI
    INNER JOIN TARGET_NAME TN
    ON AI.ANIMAL_ID = TN.ANIMAL_ID
            