-- 코드를 입력하세요
WITH SAME AS (
    SELECT USER_ID, PRODUCT_ID, COUNT(USER_ID) AS `COUNT` FROM ONLINE_SALE os
        GROUP BY USER_ID, PRODUCT_ID
)

SELECT USER_ID, PRODUCT_ID FROM SAME s
    WHERE s.COUNT > 1
        ORDER BY USER_ID, PRODUCT_ID DESC

