WITH OFFLINE_TOTAL_SALE AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALE
        FROM OFFLINE_SALE
            GROUP BY PRODUCT_ID
)


SELECT P.PRODUCT_CODE, P.PRICE * S.TOTAL_SALE AS SALES
    FROM PRODUCT P
    JOIN OFFLINE_TOTAL_SALE S
    ON P.PRODUCT_ID = S.PRODUCT_ID
        ORDER BY SALES DESC, PRODUCT_CODE