WITH CAR_NOT_AVAILABLE AS (
    SELECT DISTINCT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR C
        LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
            WHERE H.HISTORY_ID IS NOT NULL
            AND (DATE(END_DATE) >= '2022-11-01') 
            AND (DATE(START_DATE) <= '2022-11-30')
)


SELECT  CAR_ID, CAR_TYPE, FEE 
    FROM (SELECT 
          C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) AS FEE
            FROM CAR_RENTAL_COMPANY_CAR C
            JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
            ON C.CAR_TYPE = P.CAR_TYPE
                WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_NOT_AVAILABLE)
                AND C.CAR_TYPE IN ('세단', 'SUV')
                AND P.DURATION_TYPE = '30일 이상') K
        WHERE 500000 <= FEE AND FEE < 2000000
            ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC