WITH REST_RANK AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS `RANK`
        FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_RANK
    WHERE `RANK` = 1
        ORDER BY FOOD_TYPE DESC
    