-- 코드를 작성해주세요
# SELECT ID, CASE
#                 WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
#                 WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
#                 WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
#                 ELSE 'LOW'
#             END AS COLONY_NAME
#     FROM ECOLI_DATA
#         ORDER BY ID;

SELECT ID, CASE
                WHEN e.QUARTILE = 1 THEN 'CRITICAL'
                WHEN e.QUARTILE = 2 THEN 'HIGH'
                WHEN e.QUARTILE = 3 THEN 'MEDIUM'
                ELSE 'LOW'
            END AS COLONY_NAME 
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE 
            FROM ECOLI_DATA) e
ORDER BY ID;