WITH INTAKE_INTACT AS (
    SELECT ANIMAL_ID
        FROM ANIMAL_INS 
            WHERE SEX_UPON_INTAKE = 'Intact Female'
            OR SEX_UPON_INTAKE = 'Intact Male'
),
OUTCOME_NS AS (
    SELECT ANIMAL_ID
        FROM ANIMAL_OUTS
            WHERE SEX_UPON_OUTCOME = 'Spayed Female'
            OR SEX_UPON_OUTCOME = 'Neutered Male'
)

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
        WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM INTAKE_INTACT)
        AND ANIMAL_ID IN (SELECT ANIMAL_ID FROM OUTCOME_NS)
            ORDER BY ANIMAL_ID