WITH REGISTERED_USER AS (
    SELECT USER_ID
        FROM USER_INFO
            WHERE YEAR(JOINED) = 2021
),
REGISTERED_USER_COUNT AS (
    SELECT COUNT(USER_ID) AS USER_COUNT
        FROM USER_INFO
            WHERE YEAR(JOINED) = 2021
),
USER_HISTORY AS (
    SELECT U.USER_ID, S.SALES_DATE
        FROM REGISTERED_USER U
        JOIN ONLINE_SALE S
        ON U.USER_ID = S.USER_ID
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / USER_COUNT, 1) AS PURCHASED_RATIO
    FROM USER_HISTORY
    CROSS JOIN REGISTERED_USER_COUNT
        GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
            ORDER BY YEAR, MONTH
