# SELECT CAR_ID,  CASE 
#                 WHEN (DATE_FORMAT(MAX(END_DATE), '%Y-%m-%d') < '2022-10-16') THEN '대여 가능'
#                 ELSE '대여중'
#                 END AS AVAILABILITY
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     GROUP BY CAR_ID
#     ORDER BY CAR_ID DESC

SELECT A.CAR_ID, IFNULL(B.AVAILABILITY, '대여 가능') AS AVAILABILITY FROM
(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID) A
LEFT JOIN
(SELECT CAR_ID, '대여중' AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16' 
    AND '2022-10-16' <= DATE_FORMAT(END_DATE, '%Y-%m-%d')) B
ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC