-- 반납날짜가 2022년 10월 16일 이후 && 빌린 날짜가 2022년 10월 16일 이전 -> 대여중
WITH NOT_AVAILABLE AS (
    SELECT CAR_ID, '대여중' AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-10-16'
        AND END_DATE >= '2022-10-16'
)

SELECT DISTINCT(CRH.CAR_ID), IFNULL(AVAILABILITY, '대여 가능') AS AVAILABILITY 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
            LEFT OUTER JOIN NOT_AVAILABLE NA
            ON CRH.CAR_ID = NA.CAR_ID
                ORDER BY CRH.CAR_ID DESC