WITH ANIMAL_STILL_INS AS (
    SELECT I.ANIMAL_ID
        FROM ANIMAL_INS I
        LEFT JOIN ANIMAL_OUTS O
        ON I.ANIMAL_ID = O.ANIMAL_ID
            WHERE O.ANIMAL_ID IS NULL
),
ANIMAL_OLD_INS AS (
    SELECT ANIMAL_ID, NAME, DATETIME
        FROM ANIMAL_INS
            WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_STILL_INS)
                ORDER BY DATETIME
)


SELECT NAME, DATETIME
    FROM ANIMAL_OLD_INS
        LIMIT 3
