WITH FOOD_TOTAL_AMOUNT AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
        FROM FOOD_ORDER
            WHERE YEAR(PRODUCE_DATE) = 2022
            AND MONTH(PRODUCE_DATE) = 5
                GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * IFNULL(A.TOTAL_AMOUNT, 0) AS TOTAL_SALES
    FROM FOOD_PRODUCT P
    LEFT JOIN FOOD_TOTAL_AMOUNT A
    ON P.PRODUCT_ID = A.PRODUCT_ID
        WHERE A.TOTAL_AMOUNT IS NOT NULL
            ORDER BY TOTAL_SALES DESC, PRODUCT_ID
        