WITH FIRST_HALF_FLAVOR AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF
            GROUP BY FLAVOR
),
JULY_FLAVOR AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
            GROUP BY FLAVOR
),
FLAVOR_RANKED AS (
SELECT FLAVOR, TOTAL_ORDER, RANK() OVER (ORDER BY TOTAL_ORDER DESC) AS `RANK`
    FROM (SELECT H.FLAVOR, H.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER
            FROM FIRST_HALF_FLAVOR H
            LEFT JOIN JULY_FLAVOR J
            ON H.FLAVOR = J.FLAVOR
                ORDER BY TOTAL_ORDER DESC) K
)

SELECT FLAVOR FROM FLAVOR_RANKED
    WHERE `RANK` <= 3
        ORDER BY `RANK`