WITH FE AS (
    SELECT SUM(CODE) AS `FE_CODE`
        FROM SKILLCODES
            WHERE CATEGORY = 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
    FROM DEVELOPERS D
    CROSS JOIN FE F
        WHERE SKILL_CODE & FE_CODE <> 0
            ORDER BY ID
    