WITH REVIEW_RANK AS (
    SELECT MEMBER_ID, RANK() OVER (ORDER BY `COUNT` DESC) `RNK`
        FROM (SELECT MEMBER_ID, COUNT(*) AS `COUNT`
                FROM REST_REVIEW
                    GROUP BY MEMBER_ID) K
),
MOST_REVIEW AS (
    SELECT MEMBER_ID
        FROM REVIEW_RANK
            WHERE `RNK` = 1
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM MEMBER_PROFILE P
    JOIN REST_REVIEW R
    ON P.MEMBER_ID = R.MEMBER_ID
        WHERE P.MEMBER_ID IN (SELECT MEMBER_ID FROM MOST_REVIEW)
            ORDER BY REVIEW_DATE, REVIEW_TEXT