-- 코드를 작성해주세요
SELECT d1.ID, d1.GENOTYPE, d2.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA d1 LEFT JOIN ECOLI_DATA d2
                ON d1.PARENT_ID = d2.ID
    WHERE d2.ID IS NOT NULL and d1.GENOTYPE & d2.GENOTYPE = d2.GENOTYPE
        ORDER BY d1.ID;
     