WITH MAX_INFO AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
        GROUP BY FISH_TYPE
)

SELECT FI.ID, NI.FISH_NAME, FI.LENGTH FROM FISH_INFO FI
        INNER JOIN FISH_NAME_INFO NI
        ON FI.FISH_TYPE = NI.FISH_TYPE
        INNER JOIN MAX_INFO MI
        ON FI.FISH_TYPE = MI.FISH_TYPE
            WHERE FI.LENGTH = MI.LENGTH
                ORDER BY FI.ID