SELECT M.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
    FROM (SELECT EMP_NO, K.SCORE FROM (SELECT EMP_NO, SUM(SCORE) AS SCORE 
                FROM HR_GRADE
                    GROUP BY EMP_NO) K
    WHERE K.SCORE = (SELECT MAX(T.SCORE)
    FROM (SELECT EMP_NO, SUM(SCORE) AS SCORE 
                FROM HR_GRADE
                    GROUP BY EMP_NO) T)) M
    LEFT JOIN HR_EMPLOYEES E
    ON M.EMP_NO = E.EMP_NO
    

