WITH AVG_SAL AS (
    SELECT DEPT_ID, AVG(SAL) AS AVG_SAL FROM HR_EMPLOYEES
        GROUP BY DEPT_ID
)

SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(S.AVG_SAL) AS AVG_SAL
    FROM HR_DEPARTMENT D
    INNER JOIN AVG_SAL S
    ON D.DEPT_ID = S.DEPT_ID
        ORDER BY AVG_SAL DESC
        