WITH MAX_PRICE AS (
SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME FROM FOOD_PRODUCT FP
        INNER JOIN MAX_PRICE MP
        ON FP.CATEGORY = MP.CATEGORY
            WHERE FP.PRICE = MP.PRICE
            AND (FP.CATEGORY = '과자' 
                 OR FP.CATEGORY = '국'
                 OR FP.CATEGORY = '김치'
                 OR FP.CATEGORY = '식용유')
                    ORDER BY FP.PRICE DESC