WITH FISH_AVG AS (
    SELECT FISH_TYPE, AVG(LENGTH) AS AVG_LENGTH, COUNT(*) AS FISH_COUNT
        FROM (SELECT FISH_TYPE, IFNULL(M.LENGTH, 10) AS LENGTH FROM FISH_INFO M) K
            GROUP BY K.FISH_TYPE
),
FISH_MAX AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH FROM FISH_INFO
        GROUP BY FISH_TYPE
)

SELECT A.FISH_COUNT, M.MAX_LENGTH, A.FISH_TYPE FROM FISH_AVG A
        JOIN FISH_MAX M
        ON A.FISH_TYPE = M.FISH_TYPE
        WHERE A.AVG_LENGTH >= 33
        ORDER BY 3